name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [ trigger-workflow ]  # This should match the `event-type` in Repo B's workflow


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver

      - name: Test with Login Feature
        run: |
          cd tests
          pytest test_login.py -s -q -x --dashboard --html=report.html --save-screenshot --maximize 2>&1 | tee result.log   

      - name: Send logs to Slack
        if: success() || failure()
        run: |
          # Check if the workflow was triggered by repository-dispatch
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            # Use commit info from the payload for repository-dispatch
            commit_id="${{ github.event.client_payload.commit_id }}"
            commit_message="${{ github.event.client_payload.commit_message }}"
          else
            # Use commit info from the current repo (git log)
            commit_id=$(git log -1 --format='%H')
            commit_message=$(git log -1 --format='%s')
          fi
      
          echo "Commit ID: $commit_id"
          echo "Commit Message: $commit_message"
          
          
          # Get the logs and properly escape special characters
          log_contents=$(cat tests/result.log | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          
          # Debugging: Print commit details to ensure they are being captured correctly
          echo "DEBUG: Commit ID: $commit_id"
          echo "DEBUG: Commit Message: $commit_message"
          
          # Check if "failed" or "error" keywords are present in the logs to determine test result
          if [[ "$log_contents" == *"- ERROR -"* ]]; then
            result_summary="⚠️ *Test Results Summary:* Failed"
          else
            result_summary="🎉 *Test Results Summary:* Passed"
          fi
          
          # Get the link to download the GitHub artifacts
          artifact_url="https://github.com/jeremyyymrcs/Login-API-Automation/actions/runs/${{ github.run_id }}"
          
           # Create a big text art for "Automation Reports"
          header="=====================\n  AUTOMATION REPORTS  \n====================="
      
          # Send the logs, result summary, commit details, and artifact link to Slack with enhanced formatting
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"📝 *Test Logs:* \\n$log_contents\\n\\n\\n\\n$result_summary\\n\\n*━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━*\\n\\n🔑 *Commit ID:*  $commit_id\\n\\n💬 *Commit Message:* $commit_message\\n\\n*━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━*\\n\\n*📥 To download the detailed report, visit*: <$artifact_url|GitHub Artifacts>\\n\\n*✔️ Test Run Completed* \\n*━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━*‎\"}" \
          ${{ secrets.SLACK_CHANNEL_REPORT_HOOK }}

      - name: Test with API Automation
        run: |
          cd /home/runner/work/Login-API-Automation/Login-API-Automation
          pytest api_testing.py -s -v

      - name: Upload logs and screenshots from Github Action artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-result(please extract the file before viewing)
          path: |
            tests/report.html
            tests/assets/**
        if: always()  # This ensures the step runs regardless of previous success or failure


      - name: Download artifact and create a zip
        uses: actions/download-artifact@v4
        with:
          name: test-result(please extract the file before viewing)
          path: ./artifact_files

      - name: Create ZIP of report and assets
        run: |
          zip -r test-results.zip tests/report.html tests/assets/

#      - name: Send results to Slack with the zip file
#        if: success() || failure()  # Send notification regardless of success/failure
#        run: |
#          curl -X POST -H 'Content-type: application/json' \
#            --data '{
#              "text": "Test results are available! :tada:\n\nHere is the [test report](https://github.com/jeremyyymrcs/Login-API-Automation/actions/runs/${{ github.run_id }}/artifacts/${{ github.artifacts_id }})\n\nThe tests have completed. Check the results and logs.\n\nAlso, the zip file containing the results is attached below."
#            }' \
#            ${{ secrets.SLACK_CHANNEL_REPORT_HOOK }}


#      - name: Upload ZIP file to Slack
#        if: success() || failure()  # Send notification regardless of success/failure
#        run: |
#          # Upload the zip file to Slack channel using the new recommended method
#          curl -X POST https://slack.com/api/files.getUploadURLExternal \
#            -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}' \
#            -F file=@test-results.zip \
#            -F "initial_comment=Test results are available! :tada:\n\nHere is the [test report](https://github.com/jeremyyymrcs/Login-API-Automation/actions/runs/${{ github.run_id }})\n\nThe tests have completed. Check the results and logs.\n\nAlso, the zip file containing the results is attached below." \
#            -F channels=${{ secrets.SLACK_TEST_REGRESSIONAL_CHANNEL_ID }} \
#            -F "filename=test-results.zip" \
#            -F "filetype=zip"





















#      - name: Send results to Slack
#        if: success() || failure()  # Send notification regardless of success/failure
#        run: |
#          curl -X POST -H 'Content-type: application/json' \
#            --data '{
#              "text": "Test results are available! :tada:\n\nHere is the [test report](https://github.com/jeremyyymrcs/Login-API-Automation/actions/runs/${{ github.run_id }})\n\nThe tests have completed. Check the results and logs."
#            }' \
#            ${{ secrets.SLACK_CHANNEL_REPORT_HOOK }}


#name: Trigger Repo A Workflow
#
#on:
#  push:
#    branches:
#      - main  # Trigger on pushes to the main branch
#
#jobs:
#  trigger:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repo B
#        uses: actions/checkout@v4
#
#      - name: Trigger workflow in Repo A
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          repository: jeremyyymrcs/Login-API-Automation  # Name of Repo A (replace if different)
#          token: ${{ secrets.WORKFLOW_REPO_JEREMY_QA }}  # Repo B secret tokens
#          event-type: trigger-workflow  # Custom event type for Repo A to listen to
#          client-payload: '{"ref": "refs/heads/main"}'  # Specify the branch you want to trigger the workflow for
